export const movies = [
    {
      "title": "Mufasa: The Lion King",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg",
      "genre_ids": [12, 10751, 16],
      "original_language": "en",
      "original_title": "Mufasa: The Lion King",
      "overview": "A compelling journey of a cub lost and alone meets a sympathetic lion named Taka…",
      "popularity": "2984.681",
      "poster_path": "https://image.tmdb.org/t/p/w500/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg",
      "release_date": "2024-12-18",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 595
    },
    {
      "title": "Sonic the Hedgehog 3",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      "genre_ids": [28, 878, 35, 10751],
      "original_language": "en",
      "original_title": "Sonic the Hedgehog 3",
      "overview": "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow…",
      "popularity": "4090.605",
      "poster_path": "https://image.tmdb.org/t/p/w500/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      "release_date": "2024-12-19",
      "video": false,
      "vote_average": 7.6,
      "vote_count": 493
    },
    {
      "title": "Terrifier 3",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/mvDMt3JZ5zlsrXduGzj9jBEfVBT.jpg",
      "genre_ids": [27, 53],
      "original_language": "en",
      "original_title": "Terrifier 3",
      "overview": "Five years after surviving Art the Clown's Halloween massacre…",
      "popularity": "888.738",
      "poster_path": "https://image.tmdb.org/t/p/w500/ju10W5gl3PPK3b7TjEmVOZap51I.jpg",
      "release_date": "2024-10-09",
      "video": false,
      "vote_average": 6.882,
      "vote_count": 1297
    },
    {
      "title": "Anora",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/4cp40IyTpFfsT2IKpl0YlUkMBIR.jpg",
      "genre_ids": [10749, 35, 18],
      "original_language": "en",
      "original_title": "Anora",
      "overview": "A young sex worker from Brooklyn meets and impulsively marries the son of an oligarch…",
      "popularity": "883.417",
      "poster_path": "https://image.tmdb.org/t/p/w500/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
      "release_date": "2024-10-14",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 511
    },
    {
      "title": "Gladiator II",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
      "genre_ids": [28, 12, 18],
      "original_language": "en",
      "original_title": "Gladiator II",
      "overview": "Sequel to the epic that explores new challenges of power and loyalty…",
      "popularity": "951.474",
      "poster_path": "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
      "release_date": "2024-11-05",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 1041
    },
    {
      "title": "Sikandar Ka Muqaddar",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/sv3clpwOSSZO1c8i9uX4zig6Lzz.jpg",
      "genre_ids": [53, 80, 9648, 28],
      "original_language": "hi",
      "original_title": "सिकंदर का मुकद्दर",
      "overview": "After an unsolved diamond heist, a hard-nosed cop’s pursuit becomes an obsession…",
      "popularity": "966.114",
      "poster_path": "https://image.tmdb.org/t/p/w500/eWUh4rgxtgypgnOa6uGMnUt01ux.jpg",
      "release_date": "2024-11-29",
      "video": false,
      "vote_average": 5.4,
      "vote_count": 7
    },
    {
      "title": "Deadpool & Wolverine",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/dvBCdCohwWbsP5qAaglOXagDMtk.jpg",
      "genre_ids": [28, 35, 878],
      "original_language": "en",
      "original_title": "Deadpool & Wolverine",
      "overview": "Wade Wilson tries civilian life, only to suit back up when the world faces existential threat…",
      "popularity": "898.07",
      "poster_path": "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      "release_date": "2024-07-24",
      "video": false,
      "vote_average": 7.67,
      "vote_count": 0
    },
    {
      "title": "That Christmas",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/bX6dx2U4hOk1esI7mYwtD3cEKdC.jpg",
      "genre_ids": [16, 35, 10751, 14, 12],
      "original_language": "en",
      "original_title": "That Christmas",
      "overview": "An unforgettable Christmas when the worst snowstorm changes everyone's plans…",
      "popularity": "1293.13",
      "poster_path": "https://image.tmdb.org/t/p/w500/bX6dx2U4hOk1esI7mYwtD3cEKdC.jpg",
      "release_date": "2024-11-27",
      "video": false,
      "vote_average": 7.49,
      "vote_count": 96
    },
    {
      "title": "Kraven the Hunter",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/1ulX4rDlS97lbDi929PUrEi507V.jpg",
      "genre_ids": [28, 12, 53],
      "original_language": "en",
      "original_title": "Kraven the Hunter",
      "overview": "Kraven Kravinoff’s quest for vengeance rooted in family betrayal reaches brutal consequences…",
      "popularity": "908.569",
      "poster_path": "https://image.tmdb.org/t/p/w500/i47IUSsN126K11JUzqQIOi1Mg1M.jpg",
      "release_date": "2024-12-11",
      "video": false,
      "vote_average": 6.0,
      "vote_count": 24
    },
    {
      "title": "Levels",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w1280/kwXycPsLA6SV3KUOagn343TtMOf.jpg",
      "genre_ids": [28, 878, 53],
      "original_language": "en",
      "original_title": "Levels",
      "overview": "After witnessing his girlfriend's murder, reality itself is questioned…",
      "popularity": "690.039",
      "poster_path": "https://image.tmdb.org/t/p/w500/y1xm0jMIlx9Oo2a3jWNyLGm43sJ.jpg",
      "release_date": "2024-10-2",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    }
    // … add 10 more entries similarly to make 20 total
  ]
  